version: '1.0'

services:
  wanderland-server:
    image: wanderland-backend:latest
    volumes:
      - ../photo_upload:/src/main/upload/photos
    depends_on:
      - postgres14
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres14:5432/photodb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=4c6BqbLccYqbMx9rXqDPj7zbCdiK8YYA5QPxf33E

  postgres14:
    image: postgres:14.3
    restart: always
    environment:
      - POSTGRES_PASSWORD=4c6BqbLccYqbMx9rXqDPj7zbCdiK8YYA5QPxf33E
      - POSTGRES_USER=postgres
      - POSTGRES_DB=photodb
    ports:
      - "5432:5432"
    volumes:
      - my-db-postgres:/var/lib/postgresql/data

  wanderland-frontend:
    image: wanderland-client-image:2.0
    ports:
      - "4200:80"
    depends_on:
      - wanderland-server

volumes:
  my-db-postgres:





