version: '3.8'

services:
  wanderland-server:
    image: ikeller13/wanderland-server:local-1.0
    volumes:
      - ../photo_upload:/src/main/upload/photos
    depends_on:
      - postgres14
    restart: always
    ports:
      - "8080:8080"

  postgres14:
    image: postgres:14.3
    restart: always
    environment:
      - POSTGRES_PASSWORD=4c6BqbLccYqbMx9rXqDPj7zbCdiK8YYA5QPxf33E
      - POSTGRES_USER=postgres
      - POSTGRES_DB=photodb
    ports:
      - "5432:5432"
    volumes:
      - wanderland-db-postgres:/var/lib/postgresql/data

  wanderland-client:
    image: ikeller13/wanderland-client:local-1.0
    ports:
      - "4200:80"
    depends_on:
      - wanderland-server

volumes:
  wanderland-db-postgres:





