version: '3.8'
services:
  wanderland-server:
    image: ikeller13/wanderland-server:deploy-1.0
    volumes:
      - /mnt/wanderland/photos:/src/main/upload/photos
    depends_on:
      - postgres14
    restart: always
    ports:
      - "8443:8443"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres14:5432/photodb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=4c6BqbLccYqbMx9rXqDPj7zbCdiK8YYA5QPxf33E

  postgres14:
    image: postgres:14.3
    restart: always
    environment:
      - POSTGRES_PASSWORD=4c6BqbLccYqbMx9rXqDPj7zbCdiK8YYA5QPxf33E
      - POSTGRES_USER=postgres
      - POSTGRES_DB=photodb
    ports:
      - "5432:5432"
    volumes:
      - wanderland-db-postgres:/var/lib/postgresql/data

  wanderland-client:
    image: ikeller13/wanderland-client:deploy-1.0
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wanderland-server
    restart: always
    volumes:
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro

  certbot:
    image: certbot/certbot:v1.28.0
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  wanderland-db-postgres:
